// Refresh the vendored copy of the design system tokens.
//
// Values live in mateCreations (ui/tokens/*.json, DTCG) and are generated by
// Style Dictionary. They are vendored here rather than pulled as a dependency
// because mateCreations/design-system is a private repo: a runner cloning this
// site has no way to resolve @matecreations/ui.
//
// Emits two files, neither of which is edited by hand:
//   src/styles/mate-tokens.css   — the tokens, verbatim, for CSS/Tailwind
//   src/theme/tokens.generated.ts — the same semantic tokens flattened to hex,
//                                   because the site paints both themes at once
//                                   (DiptychWindow) and does color math on them
//                                   (ContrastChecker, ColorBlindnessSimulator),
//                                   neither of which can read a var().
//
// See mateCreations/DESIGN.md §9.
import { execFileSync } from 'node:child_process';
import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const MATE = process.env.MATECREATIONS ?? join(homedir(), 'code/personal/mateCreations');
const HERE = new URL('..', import.meta.url).pathname;

if (!existsSync(join(MATE, 'ui'))) {
  console.error(`mateCreations not found at ${MATE} (set MATECREATIONS to override)`);
  process.exit(1);
}

execFileSync('node', ['style-dictionary.config.mjs'], { cwd: join(MATE, 'ui'), stdio: 'ignore' });
copyFileSync(join(MATE, 'ui/dist/tokens.css'), join(HERE, 'src/styles/mate-tokens.css'));

const css = readFileSync(join(HERE, 'src/styles/mate-tokens.css'), 'utf8');
const varsIn = (selector) =>
  Object.fromEntries(
    [...css.split(selector)[1].split('}')[0].matchAll(/(--[a-z0-9-]+):\s*([^;]+);/g)].map((m) => [
      m[1],
      m[2].trim(),
    ]),
  );

const primitives = varsIn(':root');
// The semantic layer is emitted as var() references; flatten it.
const flatten = (theme) =>
  Object.fromEntries(
    Object.entries(theme).map(([name, value]) => {
      let out = value;
      for (let i = 0; i < 5; i++) {
        out = out.replace(/var\((--[a-z0-9-]+)\)/g, (_, ref) => theme[ref] ?? primitives[ref] ?? ref);
      }
      return [name, out];
    }),
  );

const themes = {
  dark: flatten(varsIn('[data-theme="dark"]')),
  light: flatten(varsIn('[data-theme="light"]')),
};

const body = Object.entries(themes)
  .map(
    ([name, tokens]) =>
      `export const ${name} = {\n` +
      Object.entries(tokens)
        .map(([token, value]) => `  '${token}': '${value}',`)
        .join('\n') +
      '\n} as const\n',
  )
  .join('\n');

writeFileSync(
  join(HERE, 'src/theme/tokens.generated.ts'),
  `// Generated by scripts/sync-tokens.mjs from mateCreations/ui. Do not edit.\n\n${body}`,
);

console.log(`synced tokens from ${MATE}`);
