import data from './upstream.json'

export interface Upstream {
  name: string
  repo: string
  what: string
  prs: number
}

/** Generated by scripts/sync-upstream.mjs from the personal site's list —
 *  edit that one (site/src/data/portfolio.js), not this. */
export const counts = data.counts
export const upstream: Upstream[] = data.upstream
